### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by juanjullian** [kreizlie/HP-EliteBook-840-G4-Hackintosh#1]
Hi my friend, i'm working with clover on the same laptop, but i'm stuck on some details while i working on trying enabling the sdcard reader.

It seems that you missed several files, like OC config files, or are you using stock OC with Kaby Lake stock plis?

Best regards

**Comment by kreizlie** [comment]
Hi friend, glad to hear from you, I disabled SD card reader after upgrading to OC, I've managed to enable SD card reader before using kext from Sinetek, but it's not stable, has bug while copying large file. I have provided OC config file on this repo friend. I use OC from official OC release, not from other hackintosher.

**Comment by kreizlie** [comment]
Oops sorry friend, I've not uploaded config file for this repo, will update tonight, you can checkout later

**Comment by kreizlie** [comment]
Hi friend, I've uploaded my OC config file.

**Comment by juanjullian** [comment]
Thanks!

So, i need only the plist and the ssdt hot pathces (which were compiled successfully)?

Also, i can't enable sd card, the sinetek driver is loaded but is unable to load any card (error 60 after changing the voltage). How do you make it work? Did you tested the cholonam fork?

**Comment by juanjullian** [comment]
Also 2: the kexts you mentioned, where is supposed to be in? L/E? S/L/E? OpenCore? i have custom kexts here and there, but as you're implementing totally new way to hack this laptop model, maybe you should upload the kets you're using to this repo with folder structures. 

Thanks a lot

**Comment by kreizlie** [comment]
Hi friend,
1: I've no plan to enable SD card reader on this laptop ( I use USB card reader) I've tested SD card reader as I mentioned before on my ProBook 430, not on this laptop (thought this issue on ProBook repo :D )
2: You should put all kexts in EFI partition (don't do the same mistake as I did when I moved from clover to opencore :D ), there is no need to modify anything under L/E or S/L/E, this will allow us to do system update, I even update to latest CatalinaOS, enabling SIP and GateKeeper, also no need to rehack after update.

If you want to move from clover to opencore, I can give you my EFI folder and you can start from there.

**Comment by juanjullian** [comment]
Thanks a lot, if you can share your efi folder i will very very appreciated. 

A read about some scripts you have to delete before migration, i will check again, and i will delete all custom kexts from S/L/E and L/E.

Thanks my friend!

**Comment by kreizlie** [comment]
@juanjullian I've uploaded an EFI folder for anyone who want to use OC on this laptop, note that **this is not a copy of my EFI**, you should create your own EFI folder, I've attached guide in many README files that you can read and follow

**Comment by juanjullian** [comment]
Thanks again, i followed the entire readme files, and it worked pretty well, until i decided to delete all custom kexts from S/L/E and L/E, now is impossible to boot, i get the apple logo with a ultra slow bar that stuck at 3/4.

**Comment by juanjullian** [comment]
Finally i can boot verbose (had to clear nvram in recovery). 
The thing is that boot hangs at apfs_module_start:1689, searching on the web people says is related to EC ACPI Method, but your config.plist has EC Patches, so if is working for you why not for me?

**Comment by kreizlie** [comment]
First thing to check is your BIOS version, I use Q85 01.09.01 Date 10/15/2019. You may get trouble with OC because our DSDT is different, I suggest you to dump and decompile your DSDT and SSDT, you can dump it using clover, and analyze my ACPI patches if it compatible with yours. In fact, the same laptop model may have different DSDT/SSDT dump.

**Comment by kreizlie** [comment]
I you need my help, just send me your ACPI dump, and I will make some adjustments based on my patches for you. Some OC replacement patches may not work on your BIOS.

**Comment by juanjullian** [comment]
Thanks my friend but now is working pretty well!!

i had to add some RTC patches and kexts to get fully working, in my case with a dw1560. Tomorrow i'll send the files and the patches so you can add them to your repo as an alternative.

Thanks for all!

**Comment by kreizlie** [comment]
Good to hear that. You can attach the file here so that I can merge to this repo. If you want to make some experiments, I can create new branch for you.

**Comment by kreizlie** [comment]
Most HP laptop has issue with RTC as the patches does not always work on every laptop, I my case, I had to replace STA method to disable the original RTC, and create a fake RTC0. Make sure you have RTC0 in ioregistryexplorer and RTC should not appear

**Comment by juanjullian** [comment]
I have the RTC device as original. With your config.plist i was unable to boot the laptop. Here is mi OC folder(url)

[https://gofile.io/d/IJV8vv](url)

 i needed to put some rtc fixes, the first one for booting and the second one for avoid the RTC power loss bios message.

Th sdcard reader is working but not after wake from sleep.

Sleep/wake is working perfectly, but after wake, hackintool hangs when i open it.

Also, i get always 100% battery status, it's strange and odd, so i have work to do, but is working!

Thanks!

**Comment by juanjullian** [comment]
i was reading about the hangs after wake from sleep and its seems to be related to lack of IMEI device, its supposed to be present because its supposed that whatevergreen rename HECI to IMEI by itself, but for some reason is no working, here's the log:

2020-06-21 00:48:21.150128-0400  localhost kernel[0]: (AppleIntelKBLGraphicsFramebuffer) <AppleIntelKBLGraphicsFramebuffer`AppleIntelFramebufferController::createMEIDriver()> [IGFB][ERROR  ] ME PCI ACPI device not found - PAVP services will be disabled - add IMEI to EFI / ACPI device list
2020-06-21 00:48:21.150161-0400  localhost kernel[0]: (AppleIntelKBLGraphicsFramebuffer) <AppleIntelKBLGraphicsFramebuffer`AppleIntelFramebufferController::createMEIDriver()> [IGFB][ERROR  ] Failed to create MEI service

**Comment by kreizlie** [comment]
Hi @juanjullian sorry for late response, did you manage to switch your hackintosh machine to OC?

**Comment by juanjullian** [comment]
Oh yes!

The problem with lag after wake from sleep is due a Bios IMEI FAILURE,
resetting bios to default settings did the trick.

Some fixes here and there, here's my updated OC folder:
https://gofile.io/d/58KBhP

I have instant wake issues sometimes, with this log: IOHIDEventDriver
product:Trackpad eventType:17 (pmset -g log), but is sometimes-

**Comment by kreizlie** [comment]
Good to hear that!

Because this laptop use SMBus Touchpad, I can only get basic gestures when using VoodooPS2, I want to try VoodooRMI from this project later to have a multi-gestures trackpad

**Comment by kreizlie** [comment]
Here it is, from VoodooSMBus
https://github.com/VoodooSMBus/VoodooRMI

**Comment by kreizlie** [comment]
@juanjullian I've upgraded my EFI folder to enable multi-gestures trackpad, it works well with all gestures enabled. I've made a release of my EFI folder, you can check it out.
