### ISSUE TITLE
Where to update kexts

### ISSUE THREAD

**Issue by DiegoDimuro** [kreizlie/HP-EliteBook-840-G4-Hackintosh#6]
Hello, im working on updating my HP to Big Sur and OC 0.6.1
Your EFI was of big help, and most of your config helped me a lot (same intel i5 and HD620). 
I need to update my kexts (whatevergreen and lilu) to support 0.6.1 and Big Sur. Do you remember where did you get your kexts (from which repos) so i can check if there are new version available.
Thank you for the help.

**Comment by kreizlie** [comment]
Hi friend, most of my kexts are from acidanthera (official opencore releases) except; NoTouchID from al3xtjames, RTL8111 from RehabMan, and VoodooI2C from VoodooI2C

**Comment by ghost** [comment]
DiegoDimuro, 

you can try the tools: Hackintool, Kextupdater. very usefull!
